microblog/urls.py
from django.conf.urls import patterns, url
from microblog import views
from django.contrib.auth.views import login, logout
from django.core.urlresolvers import reverse_lazy

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^users/$', views.users, name='users'),
    url(r'^user/(?P<id>\d+)/$', views.user_info, name='user_info'),
    url(r'^login/$', login, {'template_name': 'microblog/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': reverse_lazy('blog:index')} , name='logout')
)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url=reverse_lazy('blog:index'))),
    # url(r'^$', RedirectView.as_view(url='/~p3/wsgi/blog/')),
    url(r'^blog/', include('microblog.urls', namespace='blog'))
)

polls/urls.py
from django.conf.urls import patterns, url
from django.http import HttpResponse
from django.views.generic import ListView, DetailView

from models import Poll
import views


def stub(request, *args, **kwargs):
    return HttpResponse('stub view', mimetype="text/plain")

urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(
            queryset=Poll.objects.order_by('-pub_date')[:5],
            context_object_name='polls',
            template_name="polls/list.html"
        ),
        name="poll_list"),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Poll,
            template_name="polls/detail.html"
        ),
        name="poll_detail"),
    url(r'^(?P<pk>\d+)/vote/$',
        views.vote_view,
        name="poll_vote"),
    url(r'^(?P<pk>\d+)/result/$',
        DetailView.as_view(
            model=Poll,
            template_name="polls/result.html"),
        name="poll_result")
)

microblog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Entry(models.Model):
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=300)
    #author = models.CharField(max_length=50)
    author = models.ForeignKey(User)
    pub_date = models.DateTimeField('date published')

polls/models.py
from django.db import models
from django.utils import timezone


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('termin publikacji')

    def __unicode__(self):
        return self.question

    def published_today(self):
        now = timezone.now()
        time_delta = now - self.pub_date
        return time_delta.days == 0


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice

microblog/views.py
from django.shortcuts import render, redirect
from microblog.models import Entry
from django.utils import timezone
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404


def index(request):
    entries = Entry.objects.all().order_by('-pub_date')
    return render(request, 'microblog/index.html', {'entries': entries})

@login_required
def add(request):
    if request.method == 'POST':
        data = request.POST
        if data.get('title') and data.get('text'):
            entry = Entry(title=data['title'], text=data['text'], author=request.user, pub_date=timezone.now())
            entry.save()
            messages.success(request, 'Dodano wpis!')
        else:
            messages.warning(request, 'Brakuje danych')
    return redirect(reverse('blog:index'))

def users(request):
    users_list = User.objects.all().order_by('username')
    return render(request, 'microblog/users.html', {'users': users_list})

def user_info(request, id):
    user = get_object_or_404(User, pk=int(id))
    entries = user.entry_set.all().order_by("-pub_date")

    return render(request, 'microblog/user.html', {'user_info': user, 'entries': entries})

polls/views.py
# -*- coding: utf-8 -*-

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib import messages

from models import Poll, Choice


def vote_view(request, pk):
    poll = get_object_or_404(Poll, pk=pk)
    if request.method == "POST":
        try:
            # sprawdzenie wyboru
            # walidacja po stronie serwera jest zawsze konieczna!
            choice = poll.choice_set.get(
                        pk=request.POST.get('choice', 0))
        except Choice.DoesNotExist: # błąd — odesłanie widoku szczegółowego
            msg = u"Ups, wybierz odpowiedź, która istnieje"
            messages.add_message(request, messages.ERROR, msg)
            url = reverse('poll_detail', args=[pk, ])
        else: # zapisanie głosu i odesłanie wyników
            choice.votes += 1
            choice.save()
            messages.add_message(request, messages.INFO,
                                 u"Zagłosowałeś na %s" % choice)
            url = reverse('poll_result', args=[pk])
    else: # wysłane metodą GET — ignorujemy
        url = reverse('poll_detail', args=[pk, ])
    # przekierowanie
    return HttpResponseRedirect(redirect_to=url)

microblog/templates/microblog/entry.html
<div>
    <h2>{{ entry.title }}</h2>
    <p>
        <a class="btn btn-warning" href="{% url 'blog:user_info' entry.author.id %}">{{ entry.author }}</a>
        {{ entry.pub_date }}
    </p>
    <p>{{ entry.text }}</p>
</div>

microblog/templates/microblog/index.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
    <div class="jumbotron">
            <form action="{% url 'blog:add' %}" method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="title">Tytuł</label>
                    <br /><input type="text" name="title" id="title" placeholder="Wpisz tytuł" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="text">Tekst:</label>
                    <textarea name="text" id="text" class="form-control" placeholder="Wpisz tekst"></textarea>
                </div>
                <p><input type="submit" value="Wyślij" class="btn btn-primary btn-lg btn-block" /></p>
            </form>
      </div>
    {% endif %}




    <div class="row">
        {% if entries %}
            {% for entry in entries %}
                {% include 'microblog/entry.html' %}
            {% endfor %}
        {% else %}
            <p>Pusto</p>
        {% endif %}
    </div>
{% endblock %}

microblog/templates/microblog/login.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="width: 400px;">
{% if form.errors %}
    <div class="alert alert-danger">
        <strong>Niepoprawne dane logowania</strong>
    </div>
{% endif %}

<form method="post" action="{% url 'blog:login' %}">
{% csrf_token %}
<div class="form-group">
    {{ form.username.label_tag }}
    <input id="id_username" maxlength="254" name="username" type="text" class="form-control" />
</div>
<div class="form-group">
    {{ form.password.label_tag }}
    <input id="id_password" name="password" type="password" class="form-control" />
</div>
<div class="form-group">
    <input type="submit" value="Zaloguj się" class="btn btn-primary btn-lg btn-block" />
    <input type="hidden" name="next" value="{{ next }}" />
</div>
</form>
</div>
{% endblock %}

microblog/templates/microblog/user.html
{% extends "base.html" %}

{% block content %}
    <div class="page-header"><h1>{{ user_info.username|title }}<small style="float: right;"> wpisy użytkownika</small></h1></div>
    {% if entries %}
        {% for entry in entries %}
            {% include 'microblog/entry.html' %}
        {% endfor %}
    {% else %}
        <p>Brak wpisów</p>
    {% endif %}
{% endblock %}

microblog/templates/microblog/users.html
{% extends "base.html" %}

{% block content %}
    <div class="page-header"><h1>Użytkownicy</h1></div>
    {% if users %}
        {% for user in users %}
                <a class="btn btn-warning" href="{% url 'blog:user_info' user.id %}">{{ user.username }}</a>
        {% endfor %}
    {% else %}
        <p>Nie ma użytkowników</p>
    {% endif %}
{% endblock %}

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ poll }}</h1>
{% if poll.choice_set.count > 0 %}
<form action="{% url 'poll_vote' poll.pk %}" method="POST">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
    <div class="choice">
        <label for="choice_{{ choice.pk }}">
            <input type="radio" name="choice" id="choice_{{ choice.pk }}" value="{{ choice.pk }}"/>
            {{ choice }}
        </label>
    </div>
    {% endfor %}
    <input type="submit" name="vote" value="Głosuj"/>
</form>
{% else %}
<p>To pytanie nie udostępnia żadnych możliwości wyboru.</p>
{% endif %}
{% endblock %}

polls/templates/polls/list.html
{% extends "base.html" %}

{% block content %}
<h1>Najnowsze pytania</h1>
{% for poll in polls %}
<div class="poll">
    <h2><a href="{% url 'poll_detail' poll.pk %}">{{ poll }}</a></h2>
</div>
{% endfor %}
{% endblock %}

polls/templates/polls/result.html
{% extends "base.html" %}

{% block content %}
<h1>{{ poll }}</h1>
<ul>
    {% for choice in poll.choice_set.all %}
    <li>{{ choice }} ({{choice.votes}} głosów)</li>
    {% endfor %}
</ul>
<a href="{% url 'poll_list' %}">Powrót do listy pytań</a>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mirko</title>

    <style type="text/css">
        .custom-btn {
            width: 100px !important;
        }
    </style>


    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

    <body>

    <div class="navbar navbar-inverse">
        <div class="container" style="width: 700px;">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:index' %}">#tylkomirko</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'blog:index' %}">Strona główna</a></li>
              <li><a href="{% url 'blog:users' %}">Użytkownicy</a></li>
            </ul>

            <div class="navbar-form navbar-right">
                {% if user.is_authenticated %}
                    <a href="{% url 'blog:user_info' user.id %}" class="btn btn-info custom-btn">{{ user.username }}</a>
                    <a href="{% url 'blog:logout' %}" class="btn btn-danger custom-btn">Wyloguj się</a>
                {% else %}
                    <a href="{% url 'blog:login' %}" class="btn btn-success custom-btn">Zaloguj się</a>
                {% endif %}
            </div>

          </div><!--/.nav-collapse -->
        </div>
      </div>



        <div class="container" style="width: 700px;">
            <div class="content">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
                    <strong>{{ message }}</strong>
                </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
            </div>
        </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>